import 'dart:convert';

import 'package:apicalling/model.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as https;
class Homescreen extends StatefulWidget {
  const Homescreen({super.key});

  @override
  State<Homescreen> createState() => _HomescreenState();
}

class _HomescreenState extends State<Homescreen> {
 List<Autogenerated>autogenerate=[];
  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: fetchapi(),
      builder: (context, snapshot)  {
       if(snapshot.hasData){
       return ListView.builder(
        itemCount:10 ,
        itemBuilder: (context,index){
        return Container(
     width: 100,
     color: Colors.amber,
     margin: EdgeInsets.symmetric(horizontal: 20,vertical: 0),
     padding: EdgeInsets.symmetric( vertical: 10,horizontal: 10),
          
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            
            children: [
            Text('User is :${autogenerate[index].id}',style: TextStyle(fontSize: 20),),
            Text('User is :${autogenerate[index].title}',style: TextStyle(fontSize: 20),),
                      Text('User is :${autogenerate[index].userId}',style: TextStyle(fontSize: 20),),
                          
    
    
          ]));
          
        
       });
       
       }
       else{
        return Center(
          child: CircularProgressIndicator(),
        );
       }
      },
    );
  }
  Future<List<Autogenerated>> fetchapi() async{
    final res =await https.get(Uri.parse('https://jsonplaceholder.typicode.com/albums'));
var data=jsonDecode(res.body.toString());
if(res.statusCode==200){
  for(Map<String,dynamic>index in data){
    autogenerate.add(Autogenerated.fromJson(index));
  }
  return autogenerate;
}
else{
  return autogenerate;
}
  }
}